version: '3.7'
services:
    postgres:
        image: postgres:13.1
        restart: always
        environment:
          - POSTGRES_USER=mlevisrossi
          - POSTGRES_PASSWORD=mlevisrossi
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data