version: '3'
services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=mlevisrossi
      - POSTGRES_PASSWORD=mlevisrossi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432